
FROM python

RUN apt-get -y update
RUN apt-get -y --fix-broken install wkhtmltopdf

RUN pip install pdfkit
RUN pip install requests
RUN pip install numpy
RUN pip install pandas
RUN pip install requests
RUN pip install tabulate
RUN pip install matplotlib
RUN pip install seaborn
RUN pip install scikit-learn
